name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Install Dependencies
      run: |
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libportmidi-dev \
          libavformat-dev \
          libswscale-dev \
          libavdevice-dev \
          zlib1g-dev

    - name: Build APK
      run: buildozer -v android debug
